### ISSUE TITLE
Alchemy system

### ISSUE THREAD

**Issue by 0xfrej** [Lai0n/Wiedzminstvo#4]
Refill: with alcohest up to N times (i think 8 we will see)
every refill will shorten potions effect longetivity. After an potion depleted completely you need to create new one with all the ingredients.

every time potion will be refilled it's texture main color will be less and less full.

Oils will have N time usage and no refilling system
Bombs will be same as oils i guess

Alchemy crafthing could work somewhat like in thaum craft....you get to try recipes until you find one that works and then it remembers them so you don't have to.

It should be done somehow on the go as we don't want to limit the player to place block every time just to do one potion...maybe when implementing camp for the user it could be there ?

**Comment by Lai0n** [comment]
Actually, I've decided to make potion tiers which describe how many uses and amplifier of the result potion which will be used for base potion

Bombs, oils and other shits like this were scraped..at least for now.

System itself will be like in skyrim where each ingredient has it's own effect which player has to discover

**Comment by Lai0n** [comment]
Splitting alchemy system to separate smaller issue tickets
